### ISSUE TITLE
Update to Nextcloud 23

### ISSUE THREAD

**Issue by hpreusse** [theCalcaholic/nextcloud-co2-clock#1]
Currently the app says:

```
    <dependencies>
        <nextcloud min-version="20" max-version="22" />
    </dependencies>
```
Would be nice if this could be upgraded to 23. Thanks!

**Comment by theCalcaholic** [comment]
Of course! Thanks for reminding 👍

**Comment by theCalcaholic** [comment]
Finally got around to update this (to NC 24). Sorry for the long wait!
